---
- name: deploy site
  hosts: site
  become: yes

  tasks:
  - name: Install tomcat8
    apt:
     name: tomcat8
     state: present
  - name: install openjdk8
    apt:
     name: openjdk-8-jdk
     state: present
  - name: install maven
    apt:
     name: maven
     state: present
  - name: gitclone
    git:
     repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello'
     dest: /root/box/
     clone: yes
  - name: compile
    shell: mvn install
    args:
     chdir: /root/box/
  - name: copy war
    shell: mv /root/box/target/hello-1.0.war /var/lib/tomcat8/webapps/hello-1.0.war
  - name: start tomcat
    shell: systemctl restart tomcat8